name: HG002
fa: /nfs/projects6/chm13v2.0.fa
fq: /nfs/projects6/hg002/hprc-hifi-19k.fq.gz
hap1: /nfs/projects6/hg002/HG002.1.fa
hap2: /nfs/projects6/hg002/HG002.2.fa
trf: /nfs/projects6/human_chm13v2.0_maskedY_rCRS.trf.bed
strat:
  easy: /nfs/projects6/giab-strat/CHM13_notinalldifficultregions.bed
  hard: /nfs/projects6/giab-strat/CHM13_alldifficultregions.bed
wd: /nfs/projects6/hg002/15k-36x-seqII2.0/t2t
truths:
  - dipcall
  - svim-asm
  - hapdiff
callers:
  - sniffles
  - cutesv-w2
  - cutesv-w4
  - cutesv-w10 # default
  - SVDSS-w2 # default
  - SVDSS-w4
  - SVDSS2ht-q0.98-w2
  - SVDSS2ht-q0.98-w4
  - severus-w2
  - severus-w3 # default
  - severus-w4
  - debreak
  - svisionpro-w2
  - svisionpro-w4
  - svisionpro-w5 # default
  # - svisionpro-severus # uncomment for hg19
  - sawfish
